// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'item': string;
  'item1': string;
  'questions': string;
}
declare var cssExports: CssExports;
export = cssExports;
