// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'col': string;
  'col1': string;
  'column': string;
  'container': string;
  'description': string;
  'helloWorld': string;
  'item': string;
  'item1': string;
  'item2': string;
  'item3': string;
  'item4': string;
  'item5': string;
  'itemall': string;
  'label': string;
  'ms-Grid': string;
  'parent': string;
  'questions': string;
  'row': string;
  'subTitle': string;
  'title': string;
  'xquestions': string;
  'xxquestions': string;
}
declare var cssExports: CssExports;
export = cssExports;
