export const data = [
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': 'b942add1-5c35-410f-a201-0ead4427fb21',
    'odata.etag': '\'5\'',
    'Id': 1,
    'Title': 'Thin Capitalisation',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Other',
    'SectionL2': 'Thin Capitalisation',
    'SectionL3': null,
    'QuestionDescription': 'As  is owned by a non-resident, it is subject to the thin capitalisation regime.  The current thin capitalisation ‘safe harbour’ threshold is 60%.  A breach of this threshold would lead to denial of a portion of ’s total interest cost. \n \nThe safe harbour threshold is calculated by taking account of the interest bearing debt amount.  \nWe note that the financial statements records [$XX] of interest bearing debt.  Please confirm this is the total interest bearing debt for the period ended 30 December 1900. \n\nOR\n\nAs  holds interests in non-resident companies, it is subject to the thin capitalisation regime.  The current thin capitalisation ‘safe harbour’ threshold is 75%.  A breach of this threshold would lead to denial of a portion of ’s total interest cost.  \n\nThe safe harbour threshold is calculated by taking account the total amount of the interest bearing debt (excluding the cost of investment in CFCs) for the New Zealand group of companies.  \nWe note that the financial statements records [$XX] of interest bearing debt. Please confirm this is the total interest bearing debt for the NZ group for the period ended 30 December 1900. \n\nOR\n\nPlease confirm that all intercompany and related party charges have been considered for transfer pricing purposes.\t\t\t\t\t\t\t\t',
    'ID': 1
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': '4cc108df-d588-47f2-b92d-94250706f9a6',
    'odata.etag': '\'10\'',
    'Id': 2,
    'Title': 'Balance Sheet as at 31 December 2020',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Financial Information',
    'SectionL2': null,
    'SectionL3': null,
    'QuestionDescription': 'Balance Sheet as at 31 December 2020',
    'ID': 2
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': '8a1476ac-4e19-44a5-a46d-627f5e8cfa7a',
    'odata.etag': '\'8\'',    
    'Id': 3,
    'Title': 'Profit & Loss for the period 1 January 2020 to 31 December 2020',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Financial Information',
    'SectionL2': null,
    'SectionL3': null,
    'QuestionDescription': 'Profit & Loss for the period 1 January 2020 to 31 December 2020',
    'ID': 3
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': '06e6be5a-b1b6-473b-863c-11ab978c73d8',
    'odata.etag': '\'8\'',    
    'Id': 4,
    'Title': 'Trial Balance as at 31 December 2020',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Financial Information',
    'SectionL2': null,
    'SectionL3': null,
    'QuestionDescription': 'Trial Balance as at 31 December 2020',
    'ID': 4
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': 'a4032a46-f46d-4d1a-a1ab-2ecf1134ec1e',
    'odata.etag': '\'8\'',    
    'Id': 5,
    'Title': 'Balance Sheet movements report as at 31 December 2020',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Financial Information',
    'SectionL2': null,
    'SectionL3': null,
    'QuestionDescription': 'Balance Sheet movements report as at 31 December 2020',
    'ID': 5
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': '5945848a-3478-4e8e-9555-f33ab1ca456a',
    'odata.etag': '\'7\'',
    'Id': 6,
    'Title': 'Please provide us with the details of the accounting system you currently use. If we require a username and password to access the system and this has changed since the prior year can you please note these details also.',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Financial Information',
    'SectionL2': null,
    'SectionL3': null,
    'QuestionDescription': 'Please provide us with the details of the accounting system you currently use. If we require a username and password to access the system and this has changed since the prior year can you please note these details also.',
    'ID': 6
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': 'c3befd3a-4c76-4b27-ad25-9d796001779e',
    'odata.etag': '\'7\'',    
    'Id': 7,
    'Title': 'Please confirm that all transactions for the period ended 31 December 2020 have been processed in your accounting software and we can rely on these balances.',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Financial Information',
    'SectionL2': null,
    'SectionL3': null,
    'QuestionDescription': 'Please confirm that all transactions for the period ended 31 December 2020 have been processed in your accounting software and we can rely on these balances.',
    'ID': 7
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': '3215bf26-e445-46a9-932d-aab0ae046623',
    'odata.etag': '\'7\'',    
    'Id': 8,
    'Title': 'Please provide us with a backup of your accounting system',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Financial Information',
    'SectionL2': null,
    'SectionL3': null,
    'QuestionDescription': 'Please provide us with a backup of your accounting system',
    'ID': 8
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': '633ca28d-1d5c-4610-b93f-22eeb0850a73',
    'odata.etag': '\'7\'',    
    'Id': 9,
    'Title': 'Excel copy of the detailed trial balances, including both profit and loss and balance sheet items at 31 December 2020',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Financial Information',
    'SectionL2': null,
    'SectionL3': null,
    'QuestionDescription': 'Excel copy of the detailed trial balances, including both profit and loss and balance sheet items at 31 December 2020',
    'ID': 9
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': '5cda6afe-877e-402c-b50f-e9352086d9c1',
    'odata.etag': '\'7\'',    
    'Id': 10,
    'Title': 'Transaction listing of any foreign exchange gain/loss accounts for the period (needed for the cashflow statement)',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Financial Information',
    'SectionL2': null,
    'SectionL3': null,
    'QuestionDescription': 'Transaction listing of any foreign exchange gain/loss accounts for the period (needed for the cashflow statement)',
    'ID': 10
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': '2ad9c8a4-edaa-4387-bebc-5f2b53c53f71',
    'odata.etag': '\'7\'',    
    'Id': 11,
    'Title': 'Split of revenue items (if not included in the Trial Balance)',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Financial Information',
    'SectionL2': null,
    'SectionL3': null,
    'QuestionDescription': 'Split of revenue items (if not included in the Trial Balance)',
    'ID': 11
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': '814f6b81-ab03-4305-bb2a-fa156b0399e9',
    'odata.etag': '\'7\'',    
    'Id': 12,
    'Title': 'Copies of the latest filed tax returns/statements',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Financial Information',
    'SectionL2': null,
    'SectionL3': null,
    'QuestionDescription': 'Copies of the latest filed tax returns/statements',
    'ID': 12
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': 'cb4b96f6-0bcc-4327-8a07-219ef855b6c5',
    'odata.etag': '\'8\'',    
    'Id': 13,
    'Title': 'Copies of bank statements for all of your accounts showing the closing balances as at 31 December 2020',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Assets & Liabilities',
    'SectionL2': 'Bank',
    'SectionL3': null,
    'QuestionDescription': 'Copies of bank statements for all of your accounts showing the closing balances as at 31 December 2020',
    'ID': 13
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': '5c87df40-832e-4165-9355-d884b51eba2c',
    'odata.etag': '\'8\'',    
    'Id': 14,
    'Title': 'Copies of credit card statements for all of your accounts showing the closing balance as at 31 December 2020',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Assets & Liabilities',
    'SectionL2': 'Bank',
    'SectionL3': null,
    'QuestionDescription': 'Copies of credit card statements for all of your accounts showing the closing balance as at 31 December 2020',
    'ID': 14
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': 'b57a34b2-29f3-463c-b7dc-26d18895595c',
    'odata.etag': '\'8\'',    
    'Id': 15,
    'Title': 'Confirmation of the balance of any cash on hand as at 31 December 2020',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Assets & Liabilities',
    'SectionL2': 'Bank',
    'SectionL3': null,
    'QuestionDescription': 'Confirmation of the balance of any cash on hand as at 31 December 2020',
    'ID': 15
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': 'f112755f-69ad-4ad2-8a77-2016e6062917',
    'odata.etag': '\'8\'',    
    'Id': 16,
    'Title': 'Statements for all term deposit accounts showing the closing balance, interest rate and maturity date applicable as at 31 December 2020',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Assets & Liabilities',
    'SectionL2': 'Bank',
    'SectionL3': null,
    'QuestionDescription': 'Statements for all term deposit accounts showing the closing balance, interest rate and maturity date applicable as at 31 December 2020',
    'ID': 16
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': 'a677f1c7-b4f4-43a6-99ad-339381c2bb10',
    'odata.etag': '\'8\'',
    'Id': 17,
    'Title': 'Confirmation of the overdraft facility limit at period end and interest rate, if applicable',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Assets & Liabilities',
    'SectionL2': 'Bank',
    'SectionL3': null,
    'QuestionDescription': 'Confirmation of the overdraft facility limit at period end and interest rate, if applicable',
    'ID': 17
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': '44585d40-d2de-49d3-a99e-0ef40ef28a99',
    'odata.etag': '\'8\'',
    'Id': 18,
    'Title': 'Year end reconciliations for all bank accounts',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Assets & Liabilities',
    'SectionL2': 'Bank',
    'SectionL3': null,
    'QuestionDescription': 'Year end reconciliations for all bank accounts',
    'ID': 18
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': 'a5a0a742-6760-4003-86e7-bb75a03e552c',
    'odata.etag': '\'8\'',
    'Id': 19,
    'Title': 'If you are missing any of the information requested above please provide us with the contact details of your bank manager/s and we can request this documentation directly on your behalf.',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Assets & Liabilities',
    'SectionL2': 'Bank',
    'SectionL3': null,
    'QuestionDescription': 'If you are missing any of the information requested above please provide us with the contact details of your bank manager/s and we can request this documentation directly on your behalf.',
    'ID': 19
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': '8cc21ba4-cb70-4f7c-ac15-d840d2217d6f',
    'odata.etag': '\'8\'',
    'Id': 20,
    'Title': 'Cash flow workings with opening and closing cash reconciled to balance sheet, all eliminations processed, and line items showing the minimum requirements of NZ IAS 7, including acquisition of non-current assets shown separately to disposals.<br> - If ther',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Assets & Liabilities',
    'SectionL2': 'Bank',
    'SectionL3': null,
    'QuestionDescription': 'Cash flow workings with opening and closing cash reconciled to balance sheet, all eliminations processed, and line items showing the minimum requirements of NZ IAS 7, including acquisition of non-current assets shown separately to disposals.\n - If ther',
    'ID': 20
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': '8b78f652-5528-4b1e-ab5c-d6adedad5cfc',
    'odata.etag': '\'5\'',
    'Id': 21,
    'Title': 'Can you please provide a list of people who owed you money at 30 December 1900',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Assets & Liabilities',
    'SectionL2': 'Debtors',
    'SectionL3': null,
    'QuestionDescription': 'Can you please provide a list of people who owed you money at 30 December 1900',
    'ID': 21
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': '71c18505-afd2-4b74-84f2-c752543d5293',
    'odata.etag': '\'4\'',
    'Id': 22,
    'Title': 'Confirmation that the amount of bad debts recognised during the period, if any, and the associated code these have been put to',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Assets & Liabilities',
    'SectionL2': 'Debtors',
    'SectionL3': null,
    'QuestionDescription': 'Confirmation that the amount of bad debts recognised during the period, if any, and the associated code these have been put to',
    'ID': 22
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': '32793188-695e-4d75-94f4-af88279034e5',
    'odata.etag': '\'4\'',
    'Id': 23,
    'Title': 'Confirmation of any provision for doubtful debts as at 30 December 1900',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Assets & Liabilities',
    'SectionL2': 'Debtors',
    'SectionL3': null,
    'QuestionDescription': 'Confirmation of any provision for doubtful debts as at 30 December 1900',
    'ID': 23
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': 'f89f5b91-0d76-4906-b29e-909d6a9e8a3d',
    'odata.etag': '\'4\'',
    'Id': 24,
    'Title': 'Details of any prepayments as at 30 December 1900',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Assets & Liabilities',
    'SectionL2': 'Debtors',
    'SectionL3': null,
    'QuestionDescription': 'Details of any prepayments as at 30 December 1900',
    'ID': 24
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': '2e9087cf-41ea-468f-94de-f5205a073fc5',
    'odata.etag': '\'4\'',
    'Id': 25,
    'Title': 'Details/ a schedule of all other receivables at 30 December 1900 and provide supporting documentation.',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Assets & Liabilities',
    'SectionL2': 'Debtors',
    'SectionL3': null,
    'QuestionDescription': 'Details/ a schedule of all other receivables at 30 December 1900 and provide supporting documentation.',
    'ID': 25
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': 'de00d1dd-4eae-43cb-bf3b-c9f5cd0e71dc',
    'odata.etag': '\'4\'',
    'Id': 26,
    'Title': 'Breakdown of the accounts receivable balance',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Assets & Liabilities',
    'SectionL2': 'Debtors',
    'SectionL3': null,
    'QuestionDescription': 'Breakdown of the accounts receivable balance',
    'ID': 26
  },
  {
    'odata.type': 'SP.Data.QuestionsListItem',
    'odata.id': '9935a857-edcd-4994-a3cc-65a699986b0a',
    'odata.etag': '\'4\'',
    'Id': 27,
    'Title': 'Please provide a copy of the statements for any crop proceeds received after balance date',
    'Value': null,
    'Comments': null,
    'Response': null,
    'Link1': null,
    'Link2': null,
    'SectionL1': 'Assets & Liabilities',
    'SectionL2': 'Debtors',
    'SectionL3': null,
    'QuestionDescription': 'Please provide a copy of the statements for any crop proceeds received after balance date',
    'ID': 27
  }
];
